package execution

import (
 "bytes"; "context"; "encoding/json"; "fmt"; "io"; "net/http"; "net/url"; "strings"; "time"
)
type ComputecloudProvider struct { BaseURL string; Token string; Client *http.Client; BuildJob func(ExecutionRequest)(any,error) }
func(p *ComputecloudProvider)client()*http.Client{if p.Client!=nil{return p.Client};return &http.Client{Timeout:20*time.Second}}
func(p *ComputecloudProvider)do(ctx context.Context,method,path string,body any,idem string)([]byte,error){u,err:=url.Parse(strings.TrimRight(p.BaseURL,"/"));if err!=nil||u.Scheme==""||u.Host==""{return nil,fmt.Errorf("invalid computecloud base URL")};var r io.Reader;if body!=nil{b,e:=json.Marshal(body);if e!=nil{return nil,e};r=bytes.NewReader(b)};req,e:=http.NewRequestWithContext(ctx,method,u.String()+path,r);if e!=nil{return nil,e};req.Header.Set("Content-Type","application/json");if p.Token!=""{req.Header.Set("Authorization","Bearer "+p.Token)};if idem!=""{req.Header.Set("Idempotency-Key",idem)};res,e:=p.client().Do(req);if e!=nil{return nil,e};defer res.Body.Close();b,e:=io.ReadAll(io.LimitReader(res.Body,1<<20));if e!=nil{return nil,e};if res.StatusCode>=300{return nil,fmt.Errorf("computecloud HTTP %d: %s",res.StatusCode,strings.TrimSpace(string(b)))};return b,nil}
func(p *ComputecloudProvider)Submit(ctx context.Context,in ExecutionRequest)(ExecutionRef,error){if p.BuildJob==nil{return ExecutionRef{},fmt.Errorf("computecloud job mapper is required")};job,e:=p.BuildJob(in);if e!=nil{return ExecutionRef{},e};b,e:=p.do(ctx,http.MethodPost,"/v1/jobs",job,in.ID);if e!=nil{return ExecutionRef{},e};var v struct{ID string `json:"id"`;JobID string `json:"job_id"`};if e=json.Unmarshal(b,&v);e!=nil{return ExecutionRef{},e};if v.ID==""{v.ID=v.JobID};if v.ID==""{return ExecutionRef{},fmt.Errorf("computecloud response missing job id")};return ExecutionRef{Provider:"computecloud",ID:v.ID},nil}
func(p *ComputecloudProvider)Get(ctx context.Context,ref ExecutionRef)(ExecutionStatus,error){b,e:=p.do(ctx,http.MethodGet,"/v1/jobs/"+url.PathEscape(ref.ID),nil,"");if e!=nil{return ExecutionStatus{},e};var v struct{State string `json:"state"`};if e=json.Unmarshal(b,&v);e!=nil{return ExecutionStatus{},e};return ExecutionStatus{Ref:ref,Phase:mapComputecloudPhase(v.State),UpdatedAt:time.Now()},nil}
func(p *ComputecloudProvider)Cancel(ctx context.Context,ref ExecutionRef)error{_,e:=p.do(ctx,http.MethodPost,"/v1/jobs/"+url.PathEscape(ref.ID)+"/cancel",map[string]string{"control_id":"aicloud-"+ref.ID,"reason":"requested by aicloud"},"");return e}
func(p *ComputecloudProvider)Watch(ctx context.Context,ref ExecutionRef)(<-chan ExecutionEvent,error){ch:=make(chan ExecutionEvent,1);go func(){defer close(ch);tick:=time.NewTicker(2*time.Second);defer tick.Stop();for{s,e:=p.Get(ctx,ref);if e!=nil{return};select{case ch<-ExecutionEvent{Ref:ref,Phase:s.Phase,At:s.UpdatedAt}:case<-ctx.Done():return};if s.Phase==ExecutionCompleted||s.Phase==ExecutionFailed||s.Phase==ExecutionCancelled{return};select{case<-ctx.Done():return;case<-tick.C:}}}();return ch,nil}
func mapComputecloudPhase(s string)ExecutionPhase{switch s{case "SUCCEEDED":return ExecutionCompleted;case "FAILED":return ExecutionFailed;case "CANCELED":return ExecutionCancelled;case "RUNNING":return ExecutionStarted;default:return ExecutionQueued}}
